import { useCallback,useEffect,useMemo,useState } from 'react';
import { Search,MessageSquare,Activity,Settings,ShieldCheck,X,ArrowUpCircle } from 'lucide-react';
import { call,native,shell } from './bridge';
import type { Overview,Thread,Person,Page } from './types';
import { number } from './types';
import SearchView from './SearchView';
import ConversationsView from './ConversationsView';
import ActivityView from './ActivityView';
import SettingsView from './SettingsView';
import { createProfileSession } from './profile-session';
import SetupWizard,{ Welcome } from './SetupWizard';
import type { Onboarding } from './setup-model';
export default function App(){
  const [page,setPage]=useState<Page>('search'),[status,setStatus]=useState<Overview|null>(null),[threads,setThreads]=useState<Thread[]>([]),[people,setPeople]=useState<Person[]>([]),[error,setError]=useState(''),[conversation,setConversation]=useState<{id:string;ts?:number}|undefined>(),[searchThread,setSearchThread]=useState<string|undefined>(),[update,setUpdate]=useState(''),[settingsSection,setSettingsSection]=useState('general');
  const [onboarding,setOnboarding]=useState<Onboarding|null>(null),[wizard,setWizard]=useState(false),[choosing,setChoosing]=useState(false);
  const onError=useCallback((s:string)=>setError(s.replace(/^Error: /,'')),[]);
  const session=useMemo(()=>createProfileSession({call,switchProfile:(mode,folder)=>shell<Overview>('switch_profile',{mode,folder:folder??null}),publish:(s,t,p)=>{setStatus(s);setThreads(t);setPeople(p)},changed:()=>{setConversation(undefined);setSearchThread(undefined)},clearError:()=>setError(''),onError}),[onError]);
  const refresh=session.refresh;
  useEffect(()=>{void refresh();const timer=setInterval(()=>{void refresh()},2500);return()=>clearInterval(timer)},[refresh]);
  useEffect(()=>{if(!native)return;void Promise.all([shell<{configured:boolean}>('update_info'),call<{values:Record<string,unknown>}>('settings')]).then(async([info,settings])=>{if(info.configured&&settings.values.desktop_check_updates){const u=await shell<{version:string}|null>('check_update');if(u)setUpdate(u.version)}}).catch(()=>{})},[]);
  const loadOnboarding=useCallback(async()=>{const state=await shell<Onboarding>('onboarding_state');setOnboarding(state);setWizard(state.choice==='setup')},[]);
  useEffect(()=>{void loadOnboarding().catch(e=>onError(String(e)))},[loadOnboarding,onError]);
  const selectProfile=useCallback(async(mode:string,folder?:string)=>{await session.switchProfile(mode,folder);setOnboarding(await shell<Onboarding>('onboarding_state'))},[session]);
  async function beginSetup(){setChoosing(true);try{setOnboarding(await shell<Onboarding>('onboarding_action',{action:'begin'}));setWizard(true);setError('')}catch(e){onError(String(e))}finally{setChoosing(false)}}
  async function demo(){setChoosing(true);try{await selectProfile('demo');setOnboarding(await shell<Onboarding>('onboarding_action',{action:'demo'}));setWizard(false)}catch(e){onError(String(e))}finally{setChoosing(false)}}
  async function finishSetup(){setOnboarding(await shell<Onboarding>('onboarding_action',{action:'finish'}));setWizard(false);setPage('conversations');await refresh()}
  const start=useCallback((kind:string,messageId?:string,retry=false)=>{void call('start-job',{kind,retry,...(messageId?{messageId}:{})}).then(()=>{setPage('activity');return refresh()}).catch(e=>onError(String(e)))},[refresh,onError]);
  function open(id:string,ts?:number){setConversation({id,ts});setPage('conversations')}
  const nav:[[Page,string,typeof Search],...Array<[Page,string,typeof Search]>]=[['search','Buscar',Search],['conversations','Conversas',MessageSquare],['activity','Atividade',Activity],['settings','Ajustes',Settings]];
  if(!onboarding||!status)return <div className="onboarding-shell"><div className="onboarding-brand"><MessageSquare/>WhatMCP</div><section className="welcome-body"><h1>Abrindo seu arquivo…</h1>{error?<><p className="setup-error" role="alert">{error}</p><button onClick={()=>{void refresh();void loadOnboarding().catch(e=>onError(String(e)))}}>Tentar novamente</button></>:<p>Preparando o WhatMCP.</p>}</section></div>;
  if(onboarding.choice==='welcome')return <Welcome busy={choosing} error={error||onboarding.warning||''} onDemo={()=>void demo()} onSetup={()=>void beginSetup()}/>;
  if(wizard)return <SetupWizard status={status} state={onboarding} switchProfile={selectProfile} onState={setOnboarding} onClose={()=>{setWizard(false);if(status.jobs.some(j=>j.state==='running'))setPage('activity')}} onFinish={finishSetup}/>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><MessageSquare size={23}/></div><span>WhatMCP</span></div><nav aria-label="Navegação principal">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'selected':''} onClick={()=>{setPage(id);if(id==='settings')setSettingsSection('general')}}><Icon size={21}/>{label}{id==='activity'&&status?.jobs.some(j=>j.state==='running')?<span className="working-dot"/>:null}</button>)}</nav><div className="sidebar-bottom"><div className="local-status"><ShieldCheck size={18}/><span>{status?.demo?'Demonstração local':'Arquivo local'}</span></div>{status?<small>{number(status.messages)} mensagens · {number(status.threads)} conversas</small>:null}<small className="privacy-caption">Suas conversas, no seu computador.</small></div></aside><main>{status?.demo?<div className="demo-banner">Demonstração · mensagens fictícias <button disabled={choosing} onClick={()=>void beginSetup()}>Configurar meu WhatsApp</button></div>:!onboarding.complete?<div className="demo-banner">Configuração ainda não concluída<button disabled={choosing} onClick={()=>void beginSetup()}>Continuar configuração</button></div>:null}{update?<div className="update-banner"><ArrowUpCircle size={18}/>Versão {update} disponível<button onClick={()=>{setSettingsSection('updates');setPage('settings')}}>Ver atualização</button></div>:null}{error?<div className="error-banner" role="alert"><span>{error}</span><button className="icon-button" aria-label="Fechar aviso" onClick={()=>setError('')}><X size={18}/></button></div>:null}{!status?<div className="page"><h1>Abrindo seu arquivo…</h1><p>Preparando o WhatMCP.</p><button onClick={()=>refresh()}>Tentar novamente</button></div>:page==='search'?<SearchView key={`${status.profile}:${searchThread??'all'}`}  threads={threads} people={people} initialThread={searchThread} onOpen={open} onError={onError} onTranscribe={id=>start('transcribe',id)}/>:page==='conversations'?<ConversationsView key={status.profile} threads={threads} initial={conversation} onSearch={title=>{setSearchThread(title);setPage('search')}} onError={onError} onTranscribe={id=>start('transcribe',id)}/>:page==='activity'?<ActivityView status={status} start={start} onError={onError} onOpen={open}/>:<SettingsView onSetup={()=>void beginSetup()} switchProfile={selectProfile} initialSection={settingsSection} status={status} refresh={refresh} start={start} onError={onError}/>}</main></div>
}
