import { useEffect,useState } from 'react';
import { Search } from 'lucide-react';
import { call } from './bridge';
import type { Thread,Message } from './types';
import { date,number } from './types';
import { Avatar,Conversation,Empty,Loading } from './ui';
export default function ConversationsView({threads,initial,onError,onTranscribe,onSearch}:{threads:Thread[];initial?:{id:string;ts?:number};onError:(s:string)=>void;onTranscribe:(id:string)=>void;onSearch:(id:string)=>void}){
  const [selected,setSelected]=useState(initial?.id??threads[0]?.id??''),[around,setAround]=useState(initial?.ts),[filter,setFilter]=useState(''),[kind,setKind]=useState('all'),[messages,setMessages]=useState<Message[]>([]),[loading,setLoading]=useState(false),[day,setDay]=useState(''),[before,setBefore]=useState<{ts:number;id:string}|undefined>(),[hasMore,setHasMore]=useState(false);
  useEffect(()=>{if(threads.length&&!threads.some(t=>t.id===selected)){setSelected(threads[0].id);setAround(undefined)}},[threads,selected]);
  const current=threads.find(t=>t.id===selected),visible=messages.filter(m=>kind==='all'||kind==='audio'&&m.kind==='audio'||kind==='transcribed'&&m.transcription_text);
  useEffect(()=>{let active=true;setLoading(true);setBefore(undefined);const method=around?'conversation':'feed';const params=around?{thread_id:selected,around_ts:around,limit:100}:{thread_id:selected,limit:100};if(selected)call<any>(method,params).then(r=>{if(!active)return;const list:Message[]=Array.isArray(r)?r:r.messages;setMessages(list);setHasMore(!Array.isArray(r)&&r.hasMore);const last=list.at(-1);setBefore(last?{ts:last.ts,id:last.id}:undefined);}).catch(e=>{if(active)onError(String(e))}).finally(()=>{if(active)setLoading(false)});else setLoading(false);return()=>{active=false}},[selected,around,onError]);
  async function loadMore(){if(!before)return;const r=await call<{messages:Message[];hasMore:boolean}>('feed',{thread_id:selected,last:before,limit:100});setMessages(m=>[...m,...r.messages]);setHasMore(r.hasMore);const last=r.messages.at(-1);if(last)setBefore({ts:last.ts,id:last.id});}
  return <section className="conversations-page"><aside className="thread-list"><h1>Conversas</h1><label className="small-search"><Search size={19}/><input aria-label="Filtrar conversas" placeholder="Filtrar conversas" value={filter} onChange={e=>setFilter(e.target.value)}/></label><p className="thread-count">{number(threads.length)} conversas</p>{threads.filter(t=>(t.title??t.id).toLocaleLowerCase().includes(filter.toLocaleLowerCase())).map(t=><button key={t.id} className={`thread-row ${selected===t.id?'active':''}`} onClick={()=>{setSelected(t.id);setAround(undefined);setDay('')}}><Avatar name={t.title??t.id}/><div><h3>{t.title??t.id}</h3><small>{date(t.last_ts)}</small><p>{number(t.msg_count)} mensagens arquivadas</p></div></button>)}</aside><div className="conversation-main">{current?<><header className="conversation-header"><div><h1>{current.title??current.id}</h1><p>{current.kind==='group'?'Conversa em grupo':'Conversa individual'} · Histórico arquivado</p></div><button onClick={()=>onSearch(current.id)}><Search size={18}/>Buscar nesta conversa</button></header><div className="conversation-toolbar"><div className="text-tabs">{[['all','Todas'],['audio','Áudios'],['transcribed','Com transcrição']].map(([id,label])=><button key={id} className={kind===id?'active':''} onClick={()=>setKind(id)}>{label}</button>)}</div><label>Ir para data <input type="date" aria-label="Ir para data" value={day} onChange={e=>{setDay(e.target.value);setAround(e.target.value?new Date(e.target.value+'T12:00:00').getTime()/1000:undefined)}}/></label></div>{loading?<Loading/>:visible.length?<Conversation messages={visible} onTranscribe={onTranscribe} onError={onError}/>:<Empty title="Nenhuma mensagem nesta seleção"/>}{hasMore?<button className="load-more" onClick={()=>loadMore().catch(e=>onError(String(e)))}>Carregar mais mensagens</button>:null}<footer className="history-footer">Histórico de {date(current.first_ts)} a {date(current.last_ts)}</footer></>:<Empty title="Seu arquivo ainda não tem conversas" detail="Sincronize uma fonte ou selecione um arquivo existente em Ajustes."/>}</div></section>
}
