import { useEffect,useState } from 'react';
import { Search, X, ExternalLink, Copy } from 'lucide-react';
import { call } from './bridge';
import type { Hit,Thread,Person,Message } from './types';
import { date } from './types';
import { Avatar,Conversation,Empty,Highlight,Loading } from './ui';
type Props={threads:Thread[];people:Person[];onOpen:(id:string,ts?:number)=>void;onError:(s:string)=>void;onTranscribe:(id:string)=>void;initialThread?:string};
export default function SearchView({threads,people,onOpen,onError,onTranscribe,initialThread}:Props){
  const [query,setQuery]=useState(''),[mode,setMode]=useState('hybrid'),[thread,setThread]=useState(initialThread??''),[sender,setSender]=useState(''),[period,setPeriod]=useState('all'),[kind,setKind]=useState('all');
  const [hits,setHits]=useState<Hit[]>([]),[selected,setSelected]=useState<Hit|null>(null),[messages,setMessages]=useState<Message[]>([]),[loading,setLoading]=useState(false),[searched,setSearched]=useState(false),[notice,setNotice]=useState('');
  async function search(e:React.FormEvent){e.preventDefault();if(!query.trim())return;setLoading(true);setSearched(true);setNotice('');try{const after=period==='all'?undefined:Math.floor(Date.now()/1000)-Number(period)*86400;const r=await call<{hits:Hit[];degraded:string|null;demoSemantic:boolean}>('search',{query,mode,...(thread?{threadId:thread}:{}),...(sender?{senderId:sender}:{}),...(after?{after}:{}),kind});setHits(r.hits);setSelected(r.hits[0]??null);setNotice(r.demoSemantic?'Demonstração: busca semântica com vetores locais sintéticos.':r.degraded?'A busca por significado está incompleta; os resultados podem usar apenas texto.':'');}catch(e){onError(String(e));setHits([]);setSelected(null)}finally{setLoading(false)}}
  useEffect(()=>{let current=true;if(!selected){setMessages([]);return;}call<Message[]>('conversation',{thread_id:selected.thread_id,around_ts:selected.start_ts,limit:16}).then(v=>{if(current)setMessages(v)}).catch(e=>{if(current)onError(String(e))});return()=>{current=false}},[selected,onError]);
  return <section className="page search-page"><h1>Encontre o que ficou na conversa</h1><form onSubmit={search}><div className="search-box"><Search/><input autoFocus aria-label="Buscar mensagens" placeholder="Busque uma frase, um assunto ou uma lembrança…" value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button type="button" className="icon-button" aria-label="Limpar busca" onClick={()=>setQuery('')}><X size={20}/></button>:null}<button className="search-submit" disabled={loading||!query.trim()}>Buscar</button></div>
    <div className="segmented" role="group" aria-label="Modo de busca">{[['hybrid','Inteligente'],['bm25','Texto'],['vector','Significado']].map(([id,label])=><button type="button" key={id} className={mode===id?'selected':''} onClick={()=>setMode(id)}>{label}</button>)}</div>
    <div className="filters"><select aria-label="Conversa" value={thread} onChange={e=>setThread(e.target.value)}><option value="">Todas as conversas</option>{threads.map(t=><option key={t.id} value={t.id}>{t.title??t.id}</option>)}</select><select aria-label="Período" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Todo o histórico</option><option value="30">Últimos 30 dias</option><option value="7">Últimos 7 dias</option><option value="365">Último ano</option></select><select aria-label="Pessoa" value={sender} onChange={e=>setSender(e.target.value)}><option value="">Todas as pessoas</option>{people.map(p=><option key={p.sender_id} value={p.sender_id}>{p.sender_id==='me'?'Você':p.display_name??p.sender_id}</option>)}</select><select aria-label="Tipo de mensagem" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Mensagens e áudios</option><option value="text">Mensagens de texto</option><option value="audio">Com áudio</option></select></div>
  </form>{notice?<div className="notice" role="status">{notice}</div>:null}
  <div className="search-workspace"><div className="results"><h2>{searched?`${hits.length} resultados`:'Suas conversas, ao alcance'}</h2><p className="muted">{mode==='hybrid'?'Texto e significado combinados':mode==='bm25'?'Palavras e frases no arquivo':'Assuntos e ideias relacionados'}</p>{loading?<Loading/>:!searched?<Empty title="Encontre uma conversa importante" detail="Experimente “pagamento”, “orçamento” ou uma pergunta completa."/>:!hits.length?<Empty title="Nenhum resultado" detail="Tente outras palavras ou amplie os filtros."/>:hits.map(h=><button key={h.window_id} className={`result-row ${selected?.window_id===h.window_id?'active':''}`} onClick={()=>setSelected(h)}><Avatar name={h.speakers.split(',')[0]?.replace(/^me$/,'Você')||h.thread_title||'Conversa'}/><div><h3>{h.thread_title??h.thread_id}</h3><p className="result-meta">{h.speakers.split(', ').map(s=>s==='me'?'Você':s).join(', ')} · {date(h.start_ts)}</p><p className="result-text"><Highlight text={h.text.split('\n').slice(-3).map(s=>s.replace(/^[^:]+: /,'')).join(' ')} query={query}/></p><span className="match-label">{h.bm25_rank&&h.vec_rank?'Texto e significado':h.vec_rank?'Encontrado pelo significado':'Encontrado no texto'}</span>{!h.strong?<small className="weak-match">Correspondência aproximada</small>:null}</div></button>)}</div>
    <div className="conversation-preview">{selected?<><header><h2>{selected.thread_title??selected.thread_id}</h2><p>{date(selected.start_ts)}</p></header><Conversation messages={messages} onTranscribe={onTranscribe} onError={onError} highlight={selected.start_ts}/><footer><button className="primary" onClick={()=>onOpen(selected.thread_id,selected.start_ts)}><ExternalLink size={18}/>Abrir conversa</button><button onClick={()=>navigator.clipboard.writeText(selected.text).catch(()=>onError('Não foi possível copiar.'))}><Copy size={18}/>Copiar trecho</button></footer></>:<Empty title="O contexto aparece aqui" detail="Selecione um resultado para ler as mensagens ao redor."/>}</div>
  </div></section>
}
