import { useEffect,useState } from 'react';
import { ChevronRight,Shield,Folder,Check } from 'lucide-react';
import { call,native,shell } from './bridge';
import type { Overview } from './types';
import UpdatePanel from './UpdatePanel';
type Snapshot={values:Record<string,any>;revision:string;keyConfigured:boolean;configPath:string;platform:string;demo:boolean};
const sections=[['general','Geral'],['sync','Sincronização'],['search','Busca'],['transcription','Transcrição'],['data','Dados e acesso'],['advanced','Avançado'],['updates','Atualizações']];
export default function SettingsView({status,refresh,start,onError,switchProfile,onSetup,initialSection='general'}:{onSetup:()=>void;switchProfile:(mode:string,folder?:string)=>Promise<void>;initialSection?:string;status:Overview;refresh:()=>Promise<void>;start:(s:string)=>void;onError:(s:string)=>void}){
  const [section,setSection]=useState(initialSection),[saved,setSaved]=useState<Snapshot|null>(null),[patch,setPatch]=useState<Record<string,any>>({}),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[existing,setExisting]=useState(''),[profileConfirm,setProfileConfirm]=useState(false),[switching,setSwitching]=useState(false);
  const busy=switching||status.jobs.some(j=>j.state==='running');
  async function reload(){try{setSaved(await call('settings'));setPatch({});setMessage('')}catch(e){onError(String(e))}}
  useEffect(()=>{let active=true;setSaved(null);setPatch({});setMessage('');void call<Snapshot>('settings').then(snapshot=>{if(active)setSaved(snapshot)}).catch(e=>{if(active)onError(String(e))});return()=>{active=false}},[status.profile,onError]);
  useEffect(()=>{setSection(initialSection)},[initialSection]);
  const value=(key:string,fallback:any='')=>Object.hasOwn(patch,key)?patch[key]:saved?.values[key]??fallback;
  const set=(key:string,v:any)=>{setPatch(p=>({...p,[key]:v}));setMessage('')};
  async function save(){if(!saved)return;setSaving(true);try{const r=await call<Snapshot>('save-settings',{revision:saved.revision,patch});setSaved({...saved,...r});setPatch({});setMessage('Configurações salvas.');await refresh()}catch(e){onError(String(e))}finally{setSaving(false)}}
  async function profile(mode:string){if(switching)return;setSwitching(true);try{await switchProfile(mode,mode==='existing'?existing:undefined);setProfileConfirm(false);setMessage('Arquivo selecionado.')}catch(e){onError(String(e))}finally{setSwitching(false)}}
  const field=(key:string,label:string,fallback:any='',type='text')=><label className="field" key={key}><span>{label}</span><input type={type} value={value(key,fallback)} onChange={e=>set(key,type==='number'?Number(e.target.value):e.target.value)}/></label>;
  const toggle=(key:string,label:string,detail:string,fallback=false)=><label className="toggle-row"><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={value(key,fallback)} onChange={e=>set(key,e.target.checked)}/></label>;
  return <section className="page settings-page"><h1>Ajustes</h1><p className="muted">Deixe o WhatMCP trabalhar do seu jeito.</p><div className="settings-layout"><nav className="settings-nav" aria-label="Categorias de ajustes">{sections.map(([id,label])=><button className={section===id?'selected':''} key={id} onClick={()=>setSection(id)}>{label}<ChevronRight size={16}/></button>)}</nav><div className="settings-content">{!saved?<p>Carregando configurações…</p>:<>
  {section==='general'?<div className="settings-section"><h2>Seu arquivo de mensagens</h2><p>{status.demo?'Você está explorando uma demonstração com mensagens fictícias.':'Você está usando o perfil selecionado abaixo.'}</p><div className="profile-card"><Folder/><div><strong>{status.demo?'Demonstração':'Arquivo selecionado'}</strong><code>{status.profile}</code></div></div><p className="muted">O app lembra o perfil escolhido e o reabre na próxima execução. Um arquivo existente só é acessado após sua seleção explícita. Sincronização, transcrição e indexação alteram esse arquivo quando você inicia uma operação.</p><div className="button-row"><button disabled={busy} onClick={onSetup}>Configuração guiada</button><button disabled={!native||busy} onClick={()=>profile('demo')}>Abrir demonstração</button><button disabled={!native||busy} onClick={()=>profile('archive')}>Abrir arquivo próprio do app</button></div><h3>Usar um perfil WhatMCP existente</h3><p className="muted">Selecione a pasta que contém config.json e archive.db. O app não altera sua instalação ou o agendamento atual; operações compartilham o bloqueio do WhatMCP.</p><label className="field"><span>Pasta do perfil</span><input placeholder="Caminho da pasta, por exemplo ~/.whatmcp" value={existing} onChange={e=>setExisting(e.target.value)}/></label><button disabled={!native||busy||!existing.trim()} onClick={()=>setProfileConfirm(true)}>Selecionar este arquivo</button></div>:null}
  {section==='sync'?<div className="settings-section"><h2>Sincronização</h2><p>Atualize seu arquivo quando precisar. O app usa o bloqueio de sincronização do WhatMCP e informa quando outra operação está em andamento.</p>{field('sync_timeout_minutes','Tempo máximo por sincronização (minutos)',10,'number')}{toggle('transcription_auto_after_import','Transcrever após a importação','Usa o método e o tamanho do lote escolhidos em Transcrição.')}<div className="notice">O agendamento já instalado continua sendo gerenciado pelo WhatMCP. Este app não cria um segundo serviço ou agendador.</div>{status.platform==='win32'?<>{field('windows_waren6_path','Pasta do WAren6')}{field('windows_source_path','Pasta de origem do WhatsApp')}{field('windows_output_dir','Pasta de saída dos casos')}</>:null}</div>:null}
  {section==='search'?<div className="settings-section"><h2>Busca</h2><p>Texto encontra palavras e frases. Significado encontra assuntos relacionados; Inteligente combina os dois.</p><label className="field"><span>Modelo de embeddings</span><select disabled={status.demo} value={value('openai_model','text-embedding-3-small')} onChange={e=>set('openai_model',e.target.value)}>{status.demo?<option value="demo-local">Vetores sintéticos da demonstração</option>:null}<option>text-embedding-3-small</option><option>text-embedding-3-large</option></select></label><label className="field"><span>Dimensões dos vetores</span><input disabled={status.demo} type="number" value={value('openai_dims',1536)} onChange={e=>set('openai_dims',Number(e.target.value))}/></label><p className="muted">Mudar o modelo ou as dimensões deixa os trechos pendentes no novo espaço de busca. Os vetores anteriores são preservados.</p>{field('min_sim','Similaridade mínima',0.25,'number')}{field('strong_sim','Similaridade para destacar resultados',0.5,'number')}<label className="field"><span>Chave OpenAI {saved.keyConfigured?'· configurada':''}</span><input type="password" autoComplete="new-password" placeholder={saved.keyConfigured?'Deixe vazio para manter a chave':'Cole sua chave'} value={patch.openai_api_key??''} onChange={e=>{if(e.target.value)set('openai_api_key',e.target.value);else setPatch(p=>{const next={...p};delete next.openai_api_key;return next})}}/></label>{saved.keyConfigured?<button onClick={()=>set('openai_api_key','')}>Remover chave</button>:null}<p className="muted">A chave fica no config.json local e nunca é devolvida à interface. Busca semântica e embeddings enviam texto à OpenAI; transcrição GPT envia áudio.</p></div>:null}
  {section==='transcription'?<div className="settings-section"><h2>Transcrição</h2><label className="field"><span>Método</span><select value={value('transcription_model','')??''} onChange={e=>set('transcription_model',e.target.value||null)}><option value="">Desativada</option>{status.platform==='darwin'?<><option value="apple-speech">Apple Speech · macOS 26+</option><option value="apple-dictation">Apple Dictation · macOS 26+</option></>:null}<option value="faster-whisper">Whisper local · sem envio de áudio</option><option value="gpt-transcribe">OpenAI GPT Transcribe</option></select></label>{value('transcription_model','')==='faster-whisper'?<>{field('transcription_local_python_path','Executável Python com faster-whisper')}{field('transcription_local_model_path','Pasta do modelo Whisper local')}<p className="muted">Escolha um ambiente Python e um modelo já instalados. Nenhuma dependência é instalada aqui. Whisper processa um áudio por vez e mantém o áudio neste computador.</p></>:null}{field('transcription_default_language','Idioma','pt-BR')}{field('transcription_batch_size','Áudios por lote',100,'number')}{field('transcription_concurrency','Áudios em paralelo',1,'number')}<p className="muted">Transcrições concluídas são preservadas ao trocar de método. Arquivos ausentes aparecem como indisponíveis na Atividade.</p>{(value('transcription_model','')??'').startsWith('apple-')?<button disabled={busy||Object.keys(patch).length>0} onClick={()=>start('install-model')}>Baixar modelo Apple</button>:null}<p className="muted">Os modelos Apple podem precisar de um download. GPT Transcribe usa sua chave OpenAI e pode gerar custos.</p></div>:null}
  {section==='data'?<div className="settings-section"><h2>Dados e acesso</h2><div className="profile-card"><Shield/><div><strong>Você controla a coleta</strong><p>O acesso ao WhatsApp é usado somente ao iniciar uma sincronização.</p></div></div>{status.platform==='darwin'?<><h3>Acesso Completo ao Disco no macOS</h3><p>O macOS mantém a permissão que você concede ao app até você a remover nos Ajustes do Sistema. A autorização de cinco minutos abaixo limita a coleta dentro do WhatMCP; ela não altera a permissão do macOS.</p><button disabled={!native} onClick={()=>shell('open_fda_settings').catch(e=>onError(String(e)))}>Abrir Ajustes de Privacidade</button><hr/><h3>Autorizar a próxima coleta</h3><p>{status.captureExpiresAt>Date.now()?`Autorização válida até ${new Date(status.captureExpiresAt).toLocaleTimeString('pt-BR')}.`:'Nenhuma coleta autorizada neste momento.'}</p><div className="button-row"><button className="primary" onClick={()=>call('grant-capture').then(refresh).catch(e=>onError(String(e)))}>Autorizar por 5 minutos</button><button onClick={()=>call('revoke-capture').then(refresh).catch(e=>onError(String(e)))}>Encerrar autorização</button></div><p className="muted">Encerrar a autorização cancela a coleta deste app. O arquivo já importado permanece disponível para leitura e busca.</p></>:<p>A coleta no Windows usa sua instalação configurada do WAren6. Full Disk Access é uma permissão exclusiva do macOS.</p>}<h3>Onde seus dados ficam</h3><code className="path-block">{status.profile}</code><p className="muted">Faça backup desta pasta com o app e as tarefas de importação fechados. Nenhum banco do WhatsApp é editado pelo coletor.</p></div>:null}
  {section==='advanced'?<div className="settings-section"><h2>Avançado</h2>{field('ffmpeg_path','Executável FFmpeg')}{field('ffprobe_path','Executável FFprobe')}<p className="muted">Deixe a configuração existente ou escolha executáveis locais. Conversão de áudio usa FFmpeg e FFprobe.</p><h3>Arquivo de configuração</h3><code className="path-block">{saved.configPath}</code><p className="muted">A interface modifica apenas as opções exibidas e preserva as demais. Se o arquivo mudar em outro lugar, recarregue antes de salvar.</p><button disabled={saving} onClick={reload}>Recarregar do arquivo</button></div>:null}
  {section==='updates'?<><UpdatePanel busy={busy} onError={onError}/>{toggle('desktop_check_updates','Verificar ao abrir','Avisar quando houver uma nova versão. A instalação sempre pede confirmação.')}</>:null}
  {Object.keys(patch).length?<div className="save-bar"><p>Você tem alterações por salvar.</p><button disabled={saving} onClick={()=>setPatch({})}>Descartar</button><button className="primary" onClick={save} disabled={saving||busy}>{saving?'Salvando…':'Salvar alterações'}</button></div>:message?<p className="success"><Check size={18}/>{message}</p>:null}</>}
  </div></div>{profileConfirm?<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true"><h2>Usar este arquivo?</h2><code className="path-block">{existing}</code><p>Você poderá ler as mensagens e iniciar operações que escrevem neste perfil. Nenhuma importação começa ao selecioná-lo.</p><div className="button-row"><button onClick={()=>setProfileConfirm(false)}>Cancelar</button><button className="primary" disabled={busy} onClick={()=>profile('existing')}>{switching?'Abrindo arquivo…':'Usar arquivo'}</button></div></div></div>:null}</section>
}
